# Generated by Django 5.2.1 on 2025-05-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_name', models.CharField(max_length=250, verbose_name='نام موسیقی')),
                ('artist_name', models.CharField(max_length=250, verbose_name='نام خواننده')),
                ('label', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='پوستر آهنگ')),
                ('music_file', models.FileField(blank=True, null=True, upload_to='audio/', verbose_name='فایل آهنگ')),
                ('categorey', models.CharField(choices=[('foreign', 'خارجی'), ('old', 'قدیمی'), ('podcast', 'پادکست'), ('remix', 'ریمیکس'), ('happy', 'شاد'), ('sad', 'غمگین')], default='foreign', max_length=20, verbose_name='دسته بندی')),
            ],
        ),
    ]
