# Generated by Django 5.2.1 on 2025-05-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='categorey',
            field=models.CharField(choices=[('foreign', 'خارجی'), ('old', 'قدیمی'), ('remix', 'ریمیکس'), ('happy', 'شاد'), ('sad', 'غمگین')], default='foreign', max_length=20, verbose_name='دسته بندی'),
        ),
    ]
