# Generated by Django 5.2.1 on 2025-06-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_music_categorey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='label',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='پوستر موسیقی'),
        ),
        migrations.AlterField(
            model_name='music',
            name='music_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/', verbose_name='فایل موسیقی'),
        ),
    ]
