# Generated by Django 5.2.1 on 2025-06-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='exist',
            field=models.CharField(choices=[('موجود', 'in stock'), ('ناموجود', 'out of stock')], default='in stock', verbose_name=' موجودیت '),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default='0', max_length=15, verbose_name=' قیمت '),
        ),
        migrations.AddField(
            model_name='product',
            name='product_categorey',
            field=models.CharField(choices=[('پوشاک', 'clothes'), ('ابزار', 'tools'), ('لوازم جانبی', 'other')], default='tools', max_length=20, verbose_name='دسته بندی'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_discription',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name=' توضیحات '),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name=' تصویر محصول '),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=30, null=True, verbose_name=' نام محصول '),
        ),
        migrations.AddField(
            model_name='product',
            name='product_rate',
            field=models.CharField(default='5', max_length=15, verbose_name=' امتیاز '),
        ),
    ]
