# Generated by Django 5.2.1 on 2025-06-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_exist_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='exist',
            field=models.CharField(choices=[('in stock', 'موجود'), ('out of stock', 'ناموجود')], default='in stock', verbose_name=' موجودیت '),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_categorey',
            field=models.CharField(choices=[('clothes', 'پوشاک'), ('tools', 'ابزار'), ('other ', 'لوازم جانبی'), ('Supplement', 'دارو و مکمل')], default='tools', max_length=20, verbose_name='دسته بندی'),
        ),
    ]
