# Generated by Django 5.2.1 on 2025-06-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_exist_alter_product_product_categorey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_categorey',
            field=models.CharField(choices=[('tools', 'ابزار'), ('clothes', 'پوشاک'), ('Supplement', 'دارو و مکمل'), ('other ', 'لوازم جانبی')], default='tools', max_length=20, verbose_name='دسته بندی'),
        ),
    ]
