# Generated by Django 5.2.4 on 2025-07-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='نام دوره'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_price',
            field=models.PositiveIntegerField(blank=True, help_text='قیمت دوره به تومان', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='مدت زمان دوره به ساعت', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='long_discription',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='short_discription',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='start_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
