# Generated by Django 5.2.4 on 2025-07-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_lable',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name=' لیبل دوره'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name=' عکس'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_price',
            field=models.PositiveIntegerField(blank=True, help_text='قیمت دوره به تومان', null=True, verbose_name='قیمت '),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='مدت زمان دوره به ساعت', null=True, verbose_name='مدت زمان دوره '),
        ),
        migrations.AlterField(
            model_name='course',
            name='long_discription',
            field=models.TextField(blank=True, max_length=900, null=True, verbose_name=' توضیحات بلند'),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_discription',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='توضیحات کوتاه '),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_at',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ شروع '),
        ),
    ]
