# Generated by Django 5.2.4 on 2025-08-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_course_lable_alter_course_course_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_image',
        ),
        migrations.AddField(
            model_name='course',
            name='course_image1',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='عکس اول'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_image2',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='عکس دوم'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_image3',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='عکس سوم'),
        ),
    ]
