# Generated by Django 5.2.4 on 2025-08-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_course_course_image_course_course_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='long_discription',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name=' توضیحات بلند'),
        ),
    ]
