# Generated by Django 5.2.4 on 2025-08-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_course_long_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='long_discription',
            field=models.TextField(blank=True, max_length=15000, null=True, verbose_name=' توضیحات بلند'),
        ),
    ]
