# Generated by Django 5.2.4 on 2025-08-20 11:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_course_long_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='long_discription',
            field=ckeditor.fields.RichTextField(blank=True, max_length=15000, null=True, verbose_name=' توضیحات بلند'),
        ),
    ]
