# Generated by Django 5.2.4 on 2025-09-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_course_long_discription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='start_at',
        ),
        migrations.AddField(
            model_name='course',
            name='course_level',
            field=models.CharField(choices=[('Beginner', 'مبتدی'), ('Intermediate', 'متوسط'), ('Advanced', 'حرفه\u200cای')], default='foreign', verbose_name=' سطح دوره '),
        ),
    ]
