# Generated by Django 5.2.4 on 2025-09-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_remove_course_start_at_course_course_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_level',
            field=models.CharField(choices=[('Beginner', 'مبتدی'), ('Intermediate', 'متوسط'), ('Advanced', 'حرفه\u200cای')], default='Beginner', verbose_name=' سطح دوره '),
        ),
    ]
