# Generated by Django 5.2.1 on 2025-05-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_audio_post_video_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('sport', 'ورزشی'), ('Diet', 'رژیم غذایی'), ('tools', 'ابزار ورزشی')], default='sport', max_length=20),
        ),
    ]
