# Generated by Django 5.2.1 on 2025-05-27 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='audio',
        ),
    ]
