# Generated by Django 5.2.1 on 2025-06-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name=' نام تمرین ')),
                ('discription', models.TextField(max_length=400, verbose_name='توضیحات')),
                ('muscle', models.CharField(choices=[('shoulder', 'شانه'), ('chest', 'سینه'), ('back', 'پشت'), ('hand', 'دست'), ('abdominal and side', 'شکم و پهلو'), ('leg', 'پا'), ('calf', 'ساق پا')], default='shoulder', max_length=20, verbose_name=' عضله هدف ')),
                ('categorey', models.CharField(choices=[('hypertrophy', 'افزایش حجم'), ('weight loss', 'کاهش وزن'), ('strength training', 'افزایش قدرت')], default='hypertrophy', max_length=20, verbose_name=' دسته بندی تمرین ')),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], default='male', max_length=20, verbose_name=' جنسیت ')),
                ('video', models.FileField(blank=True, null=True, upload_to='training videos/', verbose_name=' ویدئو تمرین ')),
            ],
        ),
    ]
