# Generated by Django 5.2.1 on 2025-06-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='muscle',
            field=models.CharField(choices=[('shoulder', 'شانه'), ('chest', 'سینه'), ('back', 'پشت'), ('hand', 'دست'), ('armpit', 'زیربغل'), ('abdominal and side', 'شکم و پهلو'), ('leg', 'پا'), ('calf', 'ساق پا')], default='shoulder', max_length=20, verbose_name=' عضله هدف '),
        ),
    ]
