# Generated by Django 5.2.1 on 2025-06-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_alter_workout_muscle'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='tools',
            field=models.CharField(choices=[('bodyweight', 'وزن بدن'), ('dumbbells', 'دمبل'), ('halter and plate', 'هالتر و صفحه'), ('machine', 'دستگاه'), ('cable', 'سیمکش'), ('smith', 'دستگاه اسمیت'), ('band', 'کش ورزشی'), ('medicine ball', 'توپ'), ('kettlebells', 'دمبل روسی')], default='bodyweight', verbose_name='ابزار ها'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='discription',
            field=models.TextField(verbose_name='توضیحات'),
        ),
    ]
