# Generated by Django 5.2.4 on 2025-08-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_workout_tools_alter_workout_discription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='discription',
        ),
        migrations.AddField(
            model_name='workout',
            name='stage1',
            field=models.TextField(blank=True, null=True, verbose_name='مرحله 1 '),
        ),
        migrations.AddField(
            model_name='workout',
            name='stage2',
            field=models.TextField(blank=True, null=True, verbose_name='مرحله 2 '),
        ),
        migrations.AddField(
            model_name='workout',
            name='stage3',
            field=models.TextField(blank=True, null=True, verbose_name='مرحله 3 '),
        ),
        migrations.AddField(
            model_name='workout',
            name='stage4',
            field=models.TextField(blank=True, null=True, verbose_name='مرحله 4 '),
        ),
        migrations.AddField(
            model_name='workout',
            name='stage5',
            field=models.TextField(blank=True, null=True, verbose_name='مرحله 5 '),
        ),
    ]
