# Generated by Django 5.2.4 on 2025-08-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_remove_workout_discription_workout_stage1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='stage1',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='مرحله 1 '),
        ),
    ]
