# Generated by Django 5.2.4 on 2025-08-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0006_alter_workout_stage1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='stage1',
            field=models.TextField(blank=True, null=True, verbose_name='مرحله 1 '),
        ),
    ]
