# Generated by Django 5.2.4 on 2025-08-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0007_alter_workout_stage1'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='discription',
            field=models.TextField(blank=True, null=True, verbose_name=' توضیحات  '),
        ),
    ]
