# Generated by Django 5.2.4 on 2025-08-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0009_alter_workout_muscle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='muscle',
            field=models.CharField(choices=[('shoulder', 'شانه'), ('chest', 'سینه'), ('back', 'پشت'), ('hand', 'دست'), ('armpit', 'زیربغل'), ('abdominal and side', 'شکم و پهلو'), ('leg', 'پا'), ('calf', 'ساق پا')], default='shoulder', max_length=20, verbose_name=' عضله هدف '),
        ),
    ]
