# Generated by Django 5.2.4 on 2025-08-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0010_alter_workout_muscle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='gender',
        ),
        migrations.AddField(
            model_name='workout',
            name='gender',
            field=models.ManyToManyField(choices=[('male', 'مرد'), ('female', 'زن')], default='male', max_length=20, to='workout.workout', verbose_name=' جنسیت '),
        ),
    ]
