# Generated by Django 5.2.4 on 2025-08-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0011_remove_workout_gender_workout_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='دسته بندی')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='جنسیت')),
            ],
        ),
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام عضله')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ابزار')),
            ],
        ),
        migrations.RemoveField(
            model_name='workout',
            name='categorey',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='muscle',
        ),
        migrations.AlterField(
            model_name='workout',
            name='discription',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='stage1',
            field=models.TextField(blank=True, null=True, verbose_name='مرحله 1'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='stage2',
            field=models.TextField(blank=True, null=True, verbose_name='مرحله 2'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='stage3',
            field=models.TextField(blank=True, null=True, verbose_name='مرحله 3'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='stage4',
            field=models.TextField(blank=True, null=True, verbose_name='مرحله 4'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='stage5',
            field=models.TextField(blank=True, null=True, verbose_name='مرحله 5'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='title',
            field=models.CharField(max_length=250, verbose_name='نام تمرین'),
        ),
        migrations.RemoveField(
            model_name='workout',
            name='tools',
        ),
        migrations.AlterField(
            model_name='workout',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='training videos/', verbose_name='ویدئو تمرین'),
        ),
        migrations.AddField(
            model_name='workout',
            name='categories',
            field=models.ManyToManyField(to='workout.category', verbose_name='دسته بندی تمرین'),
        ),
        migrations.AddField(
            model_name='workout',
            name='genders',
            field=models.ManyToManyField(to='workout.gender', verbose_name='جنسیت'),
        ),
        migrations.AddField(
            model_name='workout',
            name='muscles',
            field=models.ManyToManyField(to='workout.muscle', verbose_name='عضلات هدف'),
        ),
        migrations.AddField(
            model_name='workout',
            name='tools',
            field=models.ManyToManyField(to='workout.tool', verbose_name='ابزارها'),
        ),
    ]
