# Generated by Django 5.2.4 on 2025-08-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0012_category_gender_muscle_tool_remove_workout_categorey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='stage10',
            field=models.TextField(blank=True, null=True, verbose_name='مرحله 10'),
        ),
        migrations.AddField(
            model_name='workout',
            name='stage6',
            field=models.TextField(blank=True, null=True, verbose_name='مرحله 6'),
        ),
        migrations.AddField(
            model_name='workout',
            name='stage7',
            field=models.TextField(blank=True, null=True, verbose_name='مرحله 7'),
        ),
        migrations.AddField(
            model_name='workout',
            name='stage8',
            field=models.TextField(blank=True, null=True, verbose_name='مرحله 8'),
        ),
        migrations.AddField(
            model_name='workout',
            name='stage9',
            field=models.TextField(blank=True, null=True, verbose_name='مرحله 9'),
        ),
    ]
